### ISSUE TITLE
Issue with "Hide Trends For You"

### ISSUE THREAD

**Issue by Figo135** [oslego/better-twitter#49] opened 2022-05-29 08:36 UTC
"Hide Trends For You" hides the entire right bar instead of just trends

**Comment by diyachan** [comment] 2022-06-03 05:52
I also noticed this just today; the option also removes the search bar, which I believe also a part of the right sidebar

**Comment by kinshukk** [comment] 2022-06-03 07:08
I noticed this too recently, would love a fix for this

**Comment by oslego** [comment] 2022-06-03 08:03
Confirmed, it's broken. Somebody at Twitter clumsily added the "Trending" label to the entire sidebar. The extension uses that label to target and hide the trending section.

I need to find a better approach. This mistake on Twitter's part isn't something I can guard against.

![Screenshot 2022-06-03 at 09 59 05](https://user-images.githubusercontent.com/63899/171813562-b429cc79-9d97-448f-a81d-b85b770223cb.jpg)

**Comment by kinshukk** [comment] 2022-06-04 06:50
Looks like the actual Trending div has a new label "Timeline: Trending Now", can be fixed for now
![trending_now](https://user-images.githubusercontent.com/5251243/171988221-1c2cf020-2b81-44db-aa56-98b46a290589.png)

**Comment by kinshukk** [comment] 2022-06-04 07:04
Created a PR with the small change: https://github.com/oslego/better-twitter/pull/50

**Comment by oslego** [comment] 2022-06-04 08:00
Fixed by #50

**Closed by oslego** 2022-06-04 08:00 UTC

**Comment by WyrdByWord** [comment] 2022-08-28 22:58
This problem remains for me, using the current latest (2.1.1). Thanks in advance!
