### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Kevin-W-23** [oslego/better-twitter#70] opened 2024-05-17 23:48 UTC
Better Twitter has stopped working ever since the url was changed to x.com
<img width="619" alt="Screenshot 2024-05-17 at 7 48 41 PM" src="https://github.com/oslego/better-twitter/assets/144296515/9e1ab7a6-250c-407f-8887-c104f6a7a819">

**Comment by oslego** [comment] 2024-05-18 08:37
Duplicate of #69 

Fixed by https://github.com/oslego/better-twitter/commit/0dff873c1b83bc2e3e4175a41be2d139181d427d in [version 2.1.3](https://github.com/oslego/better-twitter/releases/tag/v2.1.3)

Version 2.1.3 was already approved for the [Firefox extension](https://addons.mozilla.org/en-GB/firefox/addon/better-twitter-extension/). Pending Review for the [Chrome extension](https://chromewebstore.google.com/detail/better-twitter/illmpnnkeobcgnnjghammeohfjpjoljp?hl=en).

**Closed as not planned by oslego** 2024-05-18 08:37 UTC
